version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn app:app --reload --bind 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./app:/opt/app
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"


