swagger: "2.0"
info:
  description: "This is finance app."
  version: "0.0.1"
  title: "My Finance App"
paths:
  /usable/present:
    get:
      summary: "今月残り自由額"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Usable"
  /usable/{year}/{month}:
    get:
      summary: "未来月の残り自由額"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "month"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Usable"
  /detail/present/used:
    get:
      summary: "今月の利用明細（既に引き落とされた明細のみ）"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Detail"
  /detail/present/plan:
    get:
      summary: "今月の利用明細（予定含む）"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Detail"
  /detail/past/{year}/{month}:
    get:
      summary: "過去の指定月の利用明細"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "month"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              year:
                type: "integer"
                format: "int64"
                example: 2021
              month:
                type: "integer"
                format: "int64"
                example: 3
              details:
                type: "array"
                items:
                  $ref: "#/definitions/Detail"
  /detail/category/{id}:
    post:
      summary: "利用明細分類の指定"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "明細の分類を設定する"
        required: true
        schema:
          type: "object"
          properties:
            money:
              type: "integer"
              format: "int64"
              example: 10000
            category:
              type: "string"
              example: "衣類"
      responses:
        "201":
          description: "CREATED"
  /category/past/{year}:
    get:
      summary: "過去年度の種別利用額"
      description: ""
      produces:
        - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              year:
                type: "integer"
                format: "int64"
                example: 2021
              categories:
                type: "array"
                items:
                  $ref: "#/definitions/Category"
  /category/past/{year}/{month}:
    get:
      summary: "過去月の種別利用額"
      description: ""
      produces:
        - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "month"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              year:
                type: "integer"
                format: "int64"
                example: 2021
              month:
                type: "integer"
                format: "int64"
                example: 3
              categories:
                type: "array"
                items:
                  $ref: "#/definitions/Category"
  /plan/repeat:
    post:
      summary: "指定期間の繰り返しの使途設定"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "繰り返しの使途設定"
        required: true
        schema:
          type: "object"
          properties:
            startYear:
              type: "integer"
              format: "int64"
              example: 2021
            startMonth:
              type: "integer"
              format: "int64"
              example: 8
            endYear:
              type: "integer"
              format: "int64"
              example: 2022
            endMonth:
              type: "integer"
              format: "int64"
              example: 3
            money:
              type: "integer"
              format: "int64"
              example: 14000
            category:
              type: "string"
              example: "奨学金"
            channel:
              type: "string"
              example: "三菱UFJ銀行"
      responses:
        "201":
          description: "CREATED"
    patch:
      summary: "指定期間の繰り返しの使途修正"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "繰り返しの使途設定"
        required: true
        schema:
          type: "object"
          properties:
            startYear:
              type: "integer"
              format: "int64"
              example: 2021
            startMonth:
              type: "integer"
              format: "int64"
              example: 8
            endYear:
              type: "integer"
              format: "int64"
              example: 2022
            endMonth:
              type: "integer"
              format: "int64"
              example: 3
            money:
              type: "integer"
              format: "int64"
              example: 14000
            category:
              type: "string"
              example: "奨学金"
            channel:
              type: "string"
              example: "三菱UFJ銀行"
      responses:
        "201":
          description: "CREATED"
  /plan/shot:
    post:
      summary: "指定日の予定支出設定"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "month"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "指定日の予定支出設定"
        required: true
        schema:
          type: "object"
          properties:
            year:
              type: "integer"
              format: "int64"
              example: 2022
            month:
              type: "integer"
              format: "int64"
              example: 3
            day:
              type: "integer"
              format: "int64"
              example: 23
            money:
              type: "integer"
              format: "int64"
              example: 22000
            category:
              type: "string"
              example: "クレジットカード"
            channel:
              type: "string"
              example: "三菱UFJ銀行"
      responses:
        "201":
          description: "CREATED"
    patch:
      summary: "指定月の予定支出修正"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "year"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "month"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "指定月の予定支出修正"
        required: true
        schema:
          type: "object"
          properties:
            year:
              type: "integer"
              format: "int64"
              example: 2022
            month:
              type: "integer"
              format: "int64"
              example: 3
            day:
              type: "integer"
              format: "int64"
              example: 23
            money:
              type: "integer"
              format: "int64"
              example: 22000
            category:
              type: "string"
              example: "クレジットカード"
            channel:
              type: "string"
              example: "三菱UFJ銀行"
      responses:
        "201":
          description: "CREATED"
  /income/repeat:
    get:
      summary: "今月の月収"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              income:
                type: "integer"
                format: "int64"
                example: 202223
              flag:
                type: "string"
                example: "main"
  /income/shot:
    post:
      summary: "臨時収入追加"
      description: ""
      produces:
        - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            income:
              type: "integer"
              format: "int64"
              example: 10000
            category:
              type: "string"
              example: "撮影会"
            year:
              type: "integer"
              format: "int64"
              example: 2021
            month:
              type: "integer"
              format: "int64"
              example: 4
            day:
              type: "integer"
              format: "int64"
              example: 30
      responses:
        "200":
          description: "OK"
  /user:
    get:
      summary: "ユーザー情報取得"
      description: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "object"
            properties:
              email:
                type: "string"
    post:
      summary: "ユーザー情報登録"
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              email:
                type: "string"
              pass:
                type: "string"
      responses:
        "200":
          description: "OK"
    patch:
      summary: "ユーザー情報修正"
      description: ""
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              user_id:
                type: "integer"
                format: "int64"
              email:
                type: "string"
              pass:
                type: "string"
      responses:
        "200":
          description: "OK"
definitions:
  Usable:
    type: "object"
    properties:
      year:
        type: "integer"
        format: "int64"
      month:
        type: "integer"
        format: "int64"
      usable:
        type: "integer"
        format: "int64"
  Detail:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        type: "string"
      money:
        type: "integer"
        format: "int64"
      isplus:
        type: "boolean"
        default: false
      description: 
        type: "string"
      channel:
        type: "string"
  Category:
    type: "object"
    properties:
      category:
        type: "string"
      money:
        type: "integer"
        format: "int64"
      rate:
        type: "integer"
        format: "int64"
